FROM --platform=linux/amd64 golang:1.26-alpine AS build

WORKDIR /build

COPY go.mod ./
COPY default.pgo ./
COPY *.go ./

RUN GOAMD64=v3 CGO_ENABLED=0 go build \
      -ldflags="-s -w" \
      -trimpath \
      -pgo=auto \
      -o /out/server .

FROM --platform=linux/amd64 alpine:3.20

WORKDIR /app
COPY --from=build /out/server /app/server
COPY index.bin /app/index.bin

EXPOSE 9999
ENTRYPOINT ["/app/server"]
